version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo@2024
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\nelson.sjunior\workspace\demo-ai-chat\data:/var/lib/postgresql/data

volumes:
  postgres_data: